// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppConfig 是应用级配置。
 */
export class AppConfig {
    "log_level": string;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("log_level" in $$source)) {
            this["log_level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

/**
 * ClipboardConfig 是剪切板监听和过滤配置。
 */
export class ClipboardConfig {
    "enable": boolean;
    "debounce_ms": number;
    "max_text_length": number;
    "skip_url": boolean;
    "skip_code": boolean;
    "skip_sensitive": boolean;
    "only_translate_english": boolean;
    "english_min_ratio": number;
    "chinese_max_ratio": number;

    /** Creates a new ClipboardConfig instance. */
    constructor($$source: Partial<ClipboardConfig> = {}) {
        if (!("enable" in $$source)) {
            this["enable"] = false;
        }
        if (!("debounce_ms" in $$source)) {
            this["debounce_ms"] = 0;
        }
        if (!("max_text_length" in $$source)) {
            this["max_text_length"] = 0;
        }
        if (!("skip_url" in $$source)) {
            this["skip_url"] = false;
        }
        if (!("skip_code" in $$source)) {
            this["skip_code"] = false;
        }
        if (!("skip_sensitive" in $$source)) {
            this["skip_sensitive"] = false;
        }
        if (!("only_translate_english" in $$source)) {
            this["only_translate_english"] = false;
        }
        if (!("english_min_ratio" in $$source)) {
            this["english_min_ratio"] = 0;
        }
        if (!("chinese_max_ratio" in $$source)) {
            this["chinese_max_ratio"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipboardConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ClipboardConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClipboardConfig($$parsedSource as Partial<ClipboardConfig>);
    }
}

/**
 * LLMSettings 是设置窗口使用的模型配置。
 */
export class LLMSettings {
    "provider": string;
    "base_url": string;
    "api_key": string;
    "api_key_configured": boolean;
    "api_key_changed": boolean;
    "model": string;
    "temperature": number | null;
    "timeout_seconds": number;

    /** Creates a new LLMSettings instance. */
    constructor($$source: Partial<LLMSettings> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("api_key_configured" in $$source)) {
            this["api_key_configured"] = false;
        }
        if (!("api_key_changed" in $$source)) {
            this["api_key_changed"] = false;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("temperature" in $$source)) {
            this["temperature"] = null;
        }
        if (!("timeout_seconds" in $$source)) {
            this["timeout_seconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): LLMSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LLMSettings($$parsedSource as Partial<LLMSettings>);
    }
}

/**
 * LoggingConfig 是日志附加配置。
 */
export class LoggingConfig {
    "include_source_text": boolean;
    "max_size_mb": number;
    "max_backups": number;

    /** Creates a new LoggingConfig instance. */
    constructor($$source: Partial<LoggingConfig> = {}) {
        if (!("include_source_text" in $$source)) {
            this["include_source_text"] = false;
        }
        if (!("max_size_mb" in $$source)) {
            this["max_size_mb"] = 0;
        }
        if (!("max_backups" in $$source)) {
            this["max_backups"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoggingConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): LoggingConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoggingConfig($$parsedSource as Partial<LoggingConfig>);
    }
}

/**
 * SelectionConfig 是划词翻译的全局快捷键和兼容读取配置。
 */
export class SelectionConfig {
    "enable": boolean;
    "hotkey": string;
    "compatibility_mode": boolean;

    /** Creates a new SelectionConfig instance. */
    constructor($$source: Partial<SelectionConfig> = {}) {
        if (!("enable" in $$source)) {
            this["enable"] = false;
        }
        if (!("hotkey" in $$source)) {
            this["hotkey"] = "";
        }
        if (!("compatibility_mode" in $$source)) {
            this["compatibility_mode"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectionConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SelectionConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SelectionConfig($$parsedSource as Partial<SelectionConfig>);
    }
}

/**
 * Settings 是设置窗口使用的完整配置，API Key 仅接收新值，不返回已有明文。
 */
export class Settings {
    "app": AppConfig;
    "clipboard": ClipboardConfig;
    "selection": SelectionConfig;
    "llm": LLMSettings;
    "subtitle": SubtitleConfig;
    "logging": LoggingConfig;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("app" in $$source)) {
            this["app"] = (new AppConfig());
        }
        if (!("clipboard" in $$source)) {
            this["clipboard"] = (new ClipboardConfig());
        }
        if (!("selection" in $$source)) {
            this["selection"] = (new SelectionConfig());
        }
        if (!("llm" in $$source)) {
            this["llm"] = (new LLMSettings());
        }
        if (!("subtitle" in $$source)) {
            this["subtitle"] = (new SubtitleConfig());
        }
        if (!("logging" in $$source)) {
            this["logging"] = (new LoggingConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("app" in $$parsedSource) {
            $$parsedSource["app"] = $$createField0_0($$parsedSource["app"]);
        }
        if ("clipboard" in $$parsedSource) {
            $$parsedSource["clipboard"] = $$createField1_0($$parsedSource["clipboard"]);
        }
        if ("selection" in $$parsedSource) {
            $$parsedSource["selection"] = $$createField2_0($$parsedSource["selection"]);
        }
        if ("llm" in $$parsedSource) {
            $$parsedSource["llm"] = $$createField3_0($$parsedSource["llm"]);
        }
        if ("subtitle" in $$parsedSource) {
            $$parsedSource["subtitle"] = $$createField4_0($$parsedSource["subtitle"]);
        }
        if ("logging" in $$parsedSource) {
            $$parsedSource["logging"] = $$createField5_0($$parsedSource["logging"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * SubtitleConfig 是字幕窗口和动画配置，同时会发送给前端。
 */
export class SubtitleConfig {
    "width_percent": number;
    "bottom_offset_percent": number;
    "font_family": string;
    "font_size": number;
    "max_lines": number;
    "background_opacity": number;
    "text_color": string;
    "outline_width": number;
    "outline_color": string;
    "shadow_offset_y": number;
    "shadow_blur": number;
    "shadow_opacity": number;
    "fade_in_ms": number;
    "display_ms": number;
    "fade_out_ms": number;

    /** Creates a new SubtitleConfig instance. */
    constructor($$source: Partial<SubtitleConfig> = {}) {
        if (!("width_percent" in $$source)) {
            this["width_percent"] = 0;
        }
        if (!("bottom_offset_percent" in $$source)) {
            this["bottom_offset_percent"] = 0;
        }
        if (!("font_family" in $$source)) {
            this["font_family"] = "";
        }
        if (!("font_size" in $$source)) {
            this["font_size"] = 0;
        }
        if (!("max_lines" in $$source)) {
            this["max_lines"] = 0;
        }
        if (!("background_opacity" in $$source)) {
            this["background_opacity"] = 0;
        }
        if (!("text_color" in $$source)) {
            this["text_color"] = "";
        }
        if (!("outline_width" in $$source)) {
            this["outline_width"] = 0;
        }
        if (!("outline_color" in $$source)) {
            this["outline_color"] = "";
        }
        if (!("shadow_offset_y" in $$source)) {
            this["shadow_offset_y"] = 0;
        }
        if (!("shadow_blur" in $$source)) {
            this["shadow_blur"] = 0;
        }
        if (!("shadow_opacity" in $$source)) {
            this["shadow_opacity"] = 0;
        }
        if (!("fade_in_ms" in $$source)) {
            this["fade_in_ms"] = 0;
        }
        if (!("display_ms" in $$source)) {
            this["display_ms"] = 0;
        }
        if (!("fade_out_ms" in $$source)) {
            this["fade_out_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubtitleConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SubtitleConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubtitleConfig($$parsedSource as Partial<SubtitleConfig>);
    }
}

// Private type creation functions
const $$createType0 = AppConfig.createFrom;
const $$createType1 = ClipboardConfig.createFrom;
const $$createType2 = SelectionConfig.createFrom;
const $$createType3 = LLMSettings.createFrom;
const $$createType4 = SubtitleConfig.createFrom;
const $$createType5 = LoggingConfig.createFrom;
