// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 管理应用配置、翻译调度和桌面生命周期。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";

/**
 * CloseSettings 隐藏独立的设置窗口。
 */
export function CloseSettings(): $CancellablePromise<void> {
    return $Call.ByID(254067910);
}

/**
 * FrontendReady 表示 Vue 字幕组件已完成事件订阅，可以开始监听剪切板。
 */
export function FrontendReady(): $CancellablePromise<void> {
    return $Call.ByID(645226692);
}

/**
 * GetSettings 返回设置窗口需要的完整配置，不包含已有 API Key 明文。
 */
export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveSettings 校验并保存设置，成功后立即应用新配置。
 */
export function SaveSettings(settings: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(1949631069, settings);
}

// Private type creation functions
const $$createType0 = config$0.Settings.createFrom;
